// Generates app/src/main/res/values*/strings.xml from i18n/app-strings.json, reusing the
// desktop translations in windows/src/i18n/strings.json (keyed by English text) and
// i18n/extra.json. Usage: node android/scripts/gen-strings.mjs [--check]
// --check writes nothing and exits 1 if the committed files are stale.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const resDir = path.join(root, "app/src/main/res");
const read = (p) => JSON.parse(fs.readFileSync(p, "utf8"));

const appFile = read(path.join(root, "i18n/app-strings.json"));
const app = appFile.strings;
const untranslatable = new Set(appFile._untranslatable ?? []);
const extra = read(path.join(root, "i18n/extra.json")).strings ?? {};
const desktop = read(path.resolve(root, "../windows/src/i18n/strings.json"));
const langs = desktop.languages.filter((l) => l !== "en");

// Android resource qualifier for each language tag.
const qualifier = { "zh-Hans": "b+zh+Hans", "pt-BR": "pt-rBR", id: "in" };
const dirFor = (l) => `values-${qualifier[l] ?? l}`;

const BS = String.fromCharCode(92);
const esc = (s) =>
  s.split(BS).join(BS + BS)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/'/g, BS + "'").replace(/"/g, BS + '"')
    .replace(/^([@?])/, BS + "$1");

// Desktop placeholders ({0}, {date}) would need positional printf args; none are used yet.
if (Object.values(app).some((v) => /\{\w+\}/.test(v))) {
  console.error("Placeholders are not supported yet; use %1$s in app-strings.json.");
  process.exit(2);
}

const xml = (entries) =>
  `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by android/scripts/gen-strings.mjs. Do not edit. -->\n<resources>\n` +
  entries.map(([k, v]) => `    <string name="${k}"${untranslatable.has(k) ? ' translatable="false"' : ''}>${esc(v)}</string>`).join("\n") + `\n</resources>\n`;

const outputs = new Map();
outputs.set(path.join(resDir, "values/strings.xml"), xml(Object.entries(app)));

const missing = {};
for (const l of langs) {
  const entries = [];
  for (const [k, en] of Object.entries(app)) {
    if (untranslatable.has(k)) continue;
    const t = desktop.strings[en]?.[l] ?? extra[en]?.[l];
    if (t) entries.push([k, t]);
    else (missing[l] ??= []).push(k);
  }
  if (entries.length) outputs.set(path.join(resDir, dirFor(l), "strings.xml"), xml(entries));
}

if (process.argv.includes("--check")) {
  let stale = 0;
  for (const [file, content] of outputs) {
    if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== content) {
      console.error(`stale: ${path.relative(root, file)}`);
      stale++;
    }
  }
  process.exit(stale ? 1 : 0);
}
for (const [file, content] of outputs) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}
const total = Object.keys(app).length;
for (const l of langs) console.log(`${l}: ${total - (missing[l]?.length ?? 0)}/${total} translated`);
