// Generates app/src/main/res/values/strings.xml from i18n/app-strings.json. The app is English only.
// Usage: node android/scripts/gen-strings.mjs [--check]
// --check writes nothing and exits 1 if the committed file is stale.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const target = path.join(root, "app/src/main/res/values/strings.xml");
const app = JSON.parse(fs.readFileSync(path.join(root, "i18n/app-strings.json"), "utf8")).strings;

const BS = String.fromCharCode(92);
const esc = (s) =>
  s.split(BS).join(BS + BS)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/'/g, BS + "'").replace(/"/g, BS + '"')
    .replace(/^([@?])/, BS + "$1");

// Placeholders must be positional printf arguments (%1$s), not {name}.
if (Object.values(app).some((v) => /\{\w+\}/.test(v))) {
  console.error("Placeholders are not supported; use %1$s in app-strings.json.");
  process.exit(2);
}

const xml =
  `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by android/scripts/gen-strings.mjs. Do not edit. -->\n<resources>\n` +
  Object.entries(app).map(([k, v]) => `    <string name="${k}">${esc(v)}</string>`).join("\n") + `\n</resources>\n`;

if (process.argv.includes("--check")) {
  // Windows checkouts may turn LF into CRLF; the content is what matters.
  const stale = !fs.existsSync(target) || fs.readFileSync(target, "utf8").replace(/\r\n/g, "\n") !== xml;
  if (stale) console.error(`stale: ${path.relative(root, target)}`);
  process.exit(stale ? 1 : 0);
}
fs.writeFileSync(target, xml);
console.log(`${Object.keys(app).length} strings`);
